name: Deploy Infra Stacks

on:
  workflow_dispatch:
  push:
    paths:
      - infra/**.yaml
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy ECR CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/ecr-repo.yaml \
            --stack-name portfolio-ecr \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy EKS + Fargate Cluster Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/eks-fargate-cluster.yaml \
            --stack-name portfolio-eks-cluster \
            --capabilities CAPABILITY_NAMED_IAM